services:
  
  backend:
    # o comando build especifica o diretório onde o Dockerfile está localizado
    # neste caso, o diretório atual (./)
    build: ./
    #o comando restart sempre reinicia o contêiner se ele falhar
    restart: always
    
    labels:
      # Define o nome do serviço para o Traefik
      - traefik.enable=true
      #Define the port inside of the docker service  to be used by Traefik
      - traefik.http.services.app.loadbalancer.server.port=80
      # Make Traefik use this domain in HTTP
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`13.221.236.143`)
      # Use the traefik public network
      - traefik.docker.network=traefik-public
    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with Traefik
      - traefik-public

networks:
  traefik-public:
    # Use the previously created network "traefik-public", shared with other
    # services that need to be publicly available
    external: true