services:
  
  # Banco de dados PostgreSQL
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: kraken_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traefik-public
  
  backend:
    # o comando build especifica o diretório onde o Dockerfile está localizado
    # neste caso, o diretório atual (./)
    build: ./
    #o comando restart sempre reinicia o contêiner se ele falhar
    restart: always
    
    # Variáveis de ambiente para conectar ao PostgreSQL
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/kraken_db
    
    # Depende do banco de dados
    depends_on:
      - db
    
    labels:
      # Define o nome do serviço para o Traefik
      - traefik.enable=true
      #Define the port inside of the docker service  to be used by Traefik
      - traefik.http.services.app.loadbalancer.server.port=80
      # Make Traefik use this domain in HTTP
      - traefik.http.routers.app-http.entrypoints=web
      - traefik.http.routers.app-http.rule=Host(`13.221.236.143`)
      # Use the traefik public network
      - traefik.docker.network=traefik-public

      #--------------HTTPS----------------
      # Make Traefik use this domain in HTTPS
      - traefik.http.routers.app-https.entrypoints=websecure
      - traefik.http.routers.app-https.rule=Host(`13.221.236.143`)
      - traefik.http.routers.app-https.tls=true
      # Use the certificate resolver "le" for Let's Encrypt
      - traefik.http.routers.app-https.tls.certresolver=le
      # https redirection middlewareto redirect HTTP to HTTPS (creation of a middleware, not use yet)
      - traefik.http.middlewares.app-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.app-https-redirect.redirectscheme.permanent=true
      # Use the middleware to redirect HTTP to HTTPS (now using the middleware)
      - traefik.http.routers.app-http.middlewares=app-https-redirect
      #------------------------------------

    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with Traefik
      - traefik-public

volumes:
  # Volume para persistir os dados do PostgreSQL
  postgres_data:

networks:
  traefik-public:
    # Use the previously created network "traefik-public", shared with other
    # services that need to be publicly available
    external: true
